### ISSUE TITLE
Create custom wifi hotspot

### ISSUE THREAD

**Issue by rajat-garg1990** [vijaypatidar/AndroidWifiManager#2]
Hi, can you give a setter method where we can customize our SSID and Password, rather than any random ssids and passwords?

**Comment by vijaypatidar** [comment]
Hi @rajat-garg1990,

This library internally uses [LocalOnlyHotspot](https://developer.android.com/reference/android/net/wifi/WifiManager?hl=en#startLocalOnlyHotspot(android.net.wifi.WifiManager.LocalOnlyHotspotCallback,%20android.os.Handler)) for android version Android 8.0+ which does not allow such feature.
